[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
htr = { path = "../htr" }
criterion = { version = "0.3.5", features = ["html_reports"] }

[[bench]]
name = "transform"
path = "transform.rs"
harness = false